name: Publish
on:
  push:
    tags:
    - '*'
jobs:
  build-linux-64:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - name: setup python
        uses: actions/setup-python@v2
      - name: Compiling
        run: |
          python .github/workflows/build.py
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: .
          files: |
            klusolvex
          outPath: klusolvex_static_felipe_${{ matrix.os }}_x64.tar.gz
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "klusolvex_static_felipe_${{ matrix.os }}_x64.tar.gz"
          token: ${{ secrets.RELEASE }}
          prerelease: true
          generateReleaseNotes: true
          name: "KLUSolvex Felipe's Version ${{ matrix.os }}"