name: Publish
on:
  push:
    tags:
    - '*'
jobs:
  build-linux-64:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - name: Moving build to artifacts directory
        run: |
          sh .github/workflows/build.sh
      - name: Compress action step
        uses: a7ul/tar-action@v1.1.0
        id: compress
        with:
          command: c
          cwd: .
          files: |
            klusolvex
          outPath: klusolvex_static_felipe_linux_x64.tar.gz
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "klusolvex_static_felipe_linux_x64.tar.gz"
          token: ${{ secrets.RELEASE }}